#!/usr/bin/ash

run_hook ()
{
    if [ -n "$ppp.provider" -a -n "$ppp.device" ]; then
	ip link set "$ppp.device" up
	echo "Starting ppp"
	pppd call "$ppp.provider"
    fi
}

run_cleanuphook ()
{
    if [ -n "$ppp.provider" -a -n "$ppp.device" ]; then
	killall pppd
        ip addr flush dev "$ppp.device"
	ip link set down "$ppp.device"
    fi
}
